services:
  server:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    restart: always
    environment:
      - RACK_ENV=production
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=judge0postgrespassword
      - POSTGRES_DB=judge0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=judge0redispassword
    depends_on:
      - db
      - redis

  worker:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    restart: always
    environment:
      - RACK_ENV=production
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=judge0postgrespassword
      - POSTGRES_DB=judge0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=judge0redispassword
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.0
    environment:
      - POSTGRES_PASSWORD=judge0postgrespassword
      - POSTGRES_USER=judge0
      - POSTGRES_DB=judge0
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:6.0
    command: redis-server --requirepass judge0redispassword
    volumes:
      - redis-data:/data
    restart: always

volumes:
  postgres-data:
  redis-data:
