POSTGRES_HOST=db
POSTGRES_PORT=5432
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0postgrespassword
POSTGRES_DB=judge0
REDIS_PASSWORD=judge0redispassword
REDIS_HOST=redis
REDIS_PORT=6379
ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT=false
ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT=false
MAX_QUEUE_SIZE=5000
CPU_TIME_LIMIT=5.0
MAX_CPU_TIME_LIMIT=15.0
MEMORY_LIMIT=512000
MAX_MEMORY_LIMIT=1024000
